<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("users/new", "Create Users")) ?>
</div>

<div align="center">
    <h1>Search users</h1>
    <?php echo \Phalcon\Tag::form(array("users/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="id">Id</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("id", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="login_name">Login Of Name</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("login_name", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="password">Password</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("password", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="name">Name</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("name", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="created">Created</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("created", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="modified">Modified</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("modified", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>