<?php echo $this->getContent(); ?>

<?php echo \Phalcon\Tag::form(array("users/create", 'class' => 'form-horizontal', 'role' => 'form')) ?>
<fieldset>
<legend>Create users</legend>
<div class="form-group">
    <label for="login_name" class="col-sm-2 control-label">Login Of Name</label>
    <div class="col-sm-10">
        <?php echo \Phalcon\Tag::textField(array("login_name", 'class' => 'form-control', 'placeholder' => 'LoginName')) ?>
    </div>
</div>
<div class="form-group">
    <label for="password" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo \Phalcon\Tag::passwordField(array("password", 'class' => 'form-control', 'placeholder' => 'Password')) ?>
    </div>
</div>
<div class="form-group">
    <label for="name" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo \Phalcon\Tag::textField(array("name", 'class' => 'form-control', 'placeholder' => 'Name')) ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo \Phalcon\Tag::submitButton(array("Save", 'class' => 'btn btn-success pull-right')); ?>
    </div>
</div>
</fieldset>
<?php echo \Phalcon\Tag::endForm() ?>

<?php echo \Phalcon\Tag::linkTo(array("users", "Go Back", 'class' => 'pull-left')) ?>