<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("boards/new", "Create Boards")) ?>
</div>

<div class="col-md-6 col-md-offset-3">
    <h1>Search boards</h1>
    <?php echo \Phalcon\Tag::form(array("boards/search")) ?>
    <div class="form-group">
        <label for="id">ID</label>
        <?php echo \Phalcon\Tag::textField(array("id", "type" => "numeric", 'class' => 'form-control')) ?>
    </div>
    <div class="form-group">
        <label for="user_id">UserName</label>
        <?php echo \Phalcon\Tag::textField(array("name", "type" => "numeric", 'class' => 'form-control')) ?>
    </div>
    <div class="form-group">
        <?php echo \Phalcon\Tag::submitButton(array("Search", 'class' => 'btn btn-success pull-right')); ?>
    </div>
    <?php echo \Phalcon\Tag::endForm() ?>
</div>