<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("boards/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("boards/new", "Create boards")); ?>
        </td>
    <tr>
</table>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Content</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $boards){ ?>
        <tr>
            <td><?php echo $boards->id ?></td>
            <td><?php echo $boards->users->name ?></td>
            <td class="col-xs-4"><?php echo nl2br($boards->content) ?></td>
            <td><?php echo $boards->created ?></td>
            <td><?php echo $boards->modified ?></td>
            <td>
                <?php echo \Phalcon\Tag::linkTo(array("boards/edit/".$boards->id, "Edit", 'class' => 'btn btn-xs btn-info')); ?>
                <?php echo \Phalcon\Tag::linkTo(array("boards/delete/".$boards->id, "Delete", 'class' => 'btn btn-xs btn-warning')); ?>
            </td>
        </tr>
    <?php }
        } ?>
    </tbody>
</table>

<?php $this->partial("element/paginate") ?>